{
  "openapi": "3.0.0",
  "info": {
    "title": "Vibefy API",
    "description": "API para um streamer de músicas de forma aleatória, baseada em playlists de acordo com a vibe do usuário",
    "termsOfService": "http://localhost:3000/terms",
    "contact": {
      "email": "support@vibefy.com"
    },
    "version": "1.0.0"
  },

  "paths": {
    "/user": {
      "post": {
        "summary": "Criação de usuários",
        "description": "Esta rota faz a criação de usuários para o aplicativo",
        "tags": ["User"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/createUser"
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "Janet",
                    "email": "email@user.com",
                    "password": "1234"
                  }
                }
              }
            }
          }
        },

        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/responseUser"
                },
                "example": {
                  "name": "Joana",
                  "email": "joana@kenzie.com",
                  "playlist": [],
                  "payment": null,
                  "created_At": "December 17, 1995 03:24:00",
                  "updated_At": "December 17, 1995 03:24:00",
                  "id": "61920fb4-eb18-437b-8901-b8ce52c6ab29",
                  "avatar_img": "https://www.lance.com.br/files/article_main/uploads/2022/04/29/626c07807ccfa.jpeg",
                  "isActive": "true"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "message": "{field} is a required field"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": { "message": "Email is already being used" }
              }
            }
          }
        }
      }
    },
    "/user/profile": {
      "get": {
        "security": [{ "bearerAuth": [] }],
        "tags": ["User"],
        "summary": "Listar o próprio perfil",
        "description": "Esta rota faz a listagem do próprio perfil do usuário, esta rota necessita de autenticação",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/responseUser"
                },

                "example": {
                  "id": "6a6f480f-5360-4256-b431-875e115ef02f",
                  "name": "Vinícius",
                  "email": "henrique@user.com.br",
                  "avatar_img": "https://www.lance.com.br/files/article_main/uploads/2022/04/29/626c07807ccfa.jpeg",
                  "isActive": false,
                  "created_At": "2022-11-08",
                  "updated_At": "2022-11-08",
                  "playlist": [],
                  "payment": null
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/UnauthorizedError"
          }
        }
      },
      "patch": {
        "security": [{ "bearerAuth": [] }],
        "tags": ["User"],
        "summary": "Atualizar informações do usuário",
        "description": "Esta rota faz a atualização das informações do usuário, esta rota necessita de autenticação",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/createUser"
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "Vinícius"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Updated",
            "content": {
              "application/json": {
                "example": { "message": "User updated" }
              }
            }
          },
          "401": {
            "$ref": "#/components/UnauthorizedError"
          }
        }
      },
      "delete": {
        "security": [{ "bearerAuth": [] }],
        "tags": ["User"],
        "summary": "Desativar perfil de usuário",
        "description": "Esta rota desativa o perfil do usuário, esta rota necessita de autenticação.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "isActive": "boolean"
                }
              },
              "example": {
                "isActive": "false"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Success"
          },
          "401": {
            "$ref": "#/components/UnauthorizedError"
          }
        }
      }
    },
    "/user/profile/avatar": {
      "post": {
        "security": [{ "bearerAuth": [] }],
        "tags": ["User"],
        "summary": "Enviar imagem de usuário",
        "description": "Altera a imagem de usuário, esta rota necessita de autenticação.",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "avatar_img": { "type": "string", "format": "binary" }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Added",
            "content": {
              "application/json": {
                "example": { "message": "Image upload success" }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "Image field is required": {
                    "value": {
                      "message": "Image field is required"
                    }
                  },
                  "Wrong image format": {
                    "value": {
                      "message": "Image format must be png or jpeg"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/UnauthorizedError"
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "Login de usuário",
        "description": "Rota de login de usuário, retorna o token de usuário.",
        "tags": ["Session"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "examples": {
                "user": {
                  "value": {
                    "email": "henrique@user.com.br",
                    "password": "senhaForte123456"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "example": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhlbnJpcXVlQHVzZXIuY29tLmJyIiwidHlwZSI6InVzZXIiLCJpYXQiOjE2Njc5MTk3MTMsImV4cCI6MTY2ODAwNjExMywic3ViIjoiNmE2ZjQ4MGYtNTM2MC00MjU2LWI0MzEtODc1ZTExNWVmMDJmIn0.aOmYEgBj4t8gBUAXMz0zdVfwtYC7R1UahESIfDAf8Po"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": { "message": "Wrong email/password" }
              }
            }
          }
        }
      }
    },
    "/adm": {
      "post": {
        "summary": "Criação de usuários com privilégios de administrador",
        "description": "Esta é uma rota de destinada à criação de usuários com privilégios de administrador.",
        "tags": ["Adm"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": "string",
                  "email": "string",
                  "id": "string",
                  "avatar_img": "string"
                },
                "examples": {
                  "user": {
                    "value": {
                      "name": "henrique",
                      "email": "henrique@vibes.com",
                      "password": "senhaForte1234",
                      "admHash": "69faaa2bffab03d3e80e08ac1181526a",
                      "avatar_img": "Imagem do luffy"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "201": {
              "description": "Created",
              "content": {
                "application/json": {
                  "example": {
                    "name": "henrique",
                    "email": "henrique@vibes.com",
                    "id": "7ba51f56-b786-490a-9e3a-8df8cf565a03",
                    "avatar_img": "https://www.lance.com.br/files/article_main/uploads/2022/04/29/626c07807ccfa.jpeg"
                  }
                }
              }
            }
            
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "createUser": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "email": { "type": "string" },
          "password": { "type": "string" }
        }
      },
      "responseUser": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "email": { "type": "string" },
          "playlist": { "type": "array" },
          "payment": null,
          "created_At": { "type": "string" },
          "updated_At": { "type": "string" },
          "id": { "type": "string", "format": "uuid" },
          "avatar_img": { "type": "string" },
          "isActive": { "type": "boolean" }
        }
      },
      "Login": {
        "type": "object",
        "properties": {
          "email": { "type": "string" },
          "password": { "type": "string" }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "UnauthorizedError": {
      "description": "Unauthorized",
      "content": {
        "application/json": {
          "example": { "message": "Invalid token" }
        }
      }
    }
  }
}
